const state={words:[],filtered:[],index:0,order:'random',direction:'en-uk',topic:'All',revealed:false,history:[]};
const saved=JSON.parse(localStorage.getItem('vocabProgress')||'{}');
const known=new Set(saved.known||[]), review=new Set(saved.review||[]), fav=new Set(saved.fav||[]);
let goal=saved.goal||20;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('vocabProgress',JSON.stringify({known:[...known],review:[...review],fav:[...fav],goal}))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function topics(){const s=new Set(['General']);state.words.forEach(w=>w.topics.forEach(t=>s.add(t)));return [...s].sort()}
function applyFilter(reset=true){let arr=state.words.slice();if(state.topic!=='All')arr=arr.filter(w=>w.topics.includes(state.topic));const q=$('searchInput').value.trim().toLowerCase();if(q)arr=arr.filter(w=>w.word.toLowerCase().includes(q)||w.translation.toLowerCase().includes(q));if(state.order==='review')arr=arr.filter(w=>review.has(w.id));if(state.order==='fav')arr=arr.filter(w=>fav.has(w.id));if(state.order==='az')arr.sort((a,b)=>a.word.localeCompare(b.word,'en'));else if(state.order==='random')shuffle(arr);state.filtered=arr;if(reset)state.index=0;render()}
function current(){return state.filtered[state.index]}
function render(){updateStats();const w=current();if(!w){$('frontText').textContent='Немає слів';$('backText').textContent='Спробуй змінити фільтр.';$('answerBox').classList.remove('hidden');$('tapHint').classList.add('hidden');return}state.revealed=false;$('answerBox').classList.add('hidden');$('tapHint').classList.remove('hidden');$('topicBadge').textContent=w.topics[0]||'General';$('favBtn').textContent=fav.has(w.id)?'★':'☆';if(state.direction==='en-uk'){$('frontLabel').textContent='ENGLISH';$('frontText').textContent=w.word;$('backText').textContent=w.translation;$('pronText').textContent=w.pron?`Вимова: ${w.pron}`:'';$('ipaText').textContent=w.ipa||'';$('speakBtn').style.display='inline-block'}else{$('frontLabel').textContent='УКРАЇНСЬКА';$('frontText').textContent=w.translation;$('backText').textContent=w.word;$('pronText').textContent=w.pron?`Вимова: ${w.pron}`:'';$('ipaText').textContent=w.ipa||'';$('speakBtn').style.display='inline-block'}}
function reveal(){if(!current())return;state.revealed=true;$('answerBox').classList.remove('hidden');$('tapHint').classList.add('hidden')}
function next(push=true){if(!state.filtered.length)return;if(push)state.history.push(state.index);state.index=(state.index+1)%state.filtered.length;render()}
function prev(){if(state.history.length){state.index=state.history.pop();render()}else{state.index=(state.index-1+state.filtered.length)%state.filtered.length;render()}}
function mark(type){const w=current();if(!w)return;if(type==='known'){known.add(w.id);review.delete(w.id)}else{review.add(w.id);known.delete(w.id)}save();next();}
function updateStats(){const total=state.words.length||2978;$('knownCount').textContent=known.size;$('reviewCount').textContent=review.size;$('favCount').textContent=fav.size;$('progressText').textContent=`${known.size} / ${total}`;$('progressBar').style.width=`${Math.min(100,known.size/total*100)}%`}
function speak(){const w=current();if(!w||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w.word);u.lang='en-GB';u.rate=.85;const voices=speechSynthesis.getVoices();const gb=voices.find(v=>/en-GB/i.test(v.lang));if(gb)u.voice=gb;speechSynthesis.speak(u)}
async function boot(){const res=await fetch('words.json');state.words=await res.json();const sel=$('topicSelect');topics().forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;sel.appendChild(o)});$('goalRange').value=goal;$('goalLabel').textContent=`${goal} слів`;applyFilter()}
$('flashcard').addEventListener('click',e=>{if(e.target.closest('button'))return;reveal()});$('flashcard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();reveal()}});$('speakBtn').onclick=e=>{e.stopPropagation();speak()};$('favBtn').onclick=e=>{e.stopPropagation();const w=current();if(!w)return;fav.has(w.id)?fav.delete(w.id):fav.add(w.id);save();render()};$('knowBtn').onclick=()=>mark('known');$('dontKnowBtn').onclick=()=>mark('review');$('nextBtn').onclick=()=>next();$('prevBtn').onclick=prev;$('shuffleBtn').onclick=()=>{shuffle(state.filtered);state.index=0;render()};$('topicSelect').onchange=e=>{state.topic=e.target.value;applyFilter()};$('directionSelect').onchange=e=>{state.direction=e.target.value;render()};$('searchInput').oninput=()=>applyFilter();document.querySelectorAll('#orderControl button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#orderControl button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.order=b.dataset.order;applyFilter()});$('goalRange').oninput=e=>{$('goalLabel').textContent=`${e.target.value} слів`};$('goalRange').onchange=e=>{goal=+e.target.value;save()};$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('vocabTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('vocabTheme')==='dark')document.body.classList.add('dark');if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));boot();
